template: Hello, %s!
defaultName: Stranger

server:
  applicationConnectors:
  - type: http
    port: 9595
  adminConnectors:
  - type: http
    port: 9596

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/userServiceDb
